apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
          #name: postgres-deployment
    app: voting-app-demo
spec:
  replicas: 1
  selector:
     matchLabels:
        name: prostgres-pod
        app: voting-app-demo
  template:
    metadata: 
      name: prostgres-pod
      labels:
        name: prostgres-pod
        app: voting-app-demo
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          ports:
            - containerPort: 5432
