apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
       name: votting-pod
       app: demo-voting-app
  template:
    metadata: 
      name: votting-pod
      labels: 
        name: votting-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80